import { ComponentDoc } from "./doc-model";
import {
  buttonDoc,
  inputDoc,
  textareaDoc,
  checkboxDoc,
  switchDoc,
  radioGroupDoc,
  badgeDoc,
  alertDoc,
  dialogDoc,
  cardDoc,
  dividerDoc,
  avatarDoc,
  spinnerDoc,
  tagDoc,
  progressBarDoc,
  tabsDoc,
  accordionDoc,
  tooltipDoc,
} from "@onyx/ui/components";

export const COMPONENT_DOCS: ComponentDoc[] = [
  buttonDoc,
  inputDoc,
  textareaDoc,
  checkboxDoc,
  switchDoc,
  radioGroupDoc,
  badgeDoc,
  alertDoc,
  dialogDoc,
  cardDoc,
  dividerDoc,
  avatarDoc,
  spinnerDoc,
  tagDoc,
  progressBarDoc,
  tabsDoc,
  accordionDoc,
  tooltipDoc,
];
